version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
    container_name: mysql
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQL_PORT:3306
    expose:
      - $MYSQL_PORT

  pg:
    image: postgres:11
    container_name: pg
    env_file: ./.env
    environment:
      - POSTGRES_DB=$PG_DATABASE
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
    ports:
      - $PG_PORT:5432
    expose:
      - $PG_PORT
