name: test
on:
  - push
  - pull_request
jobs:
  linux:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis
    strategy:
      matrix:
        node-version:
          - 16.15.1
          - 18.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run tests
        run: npm test
        env:
          PG_HOST: postgres
          PG_PORT: 5432
          PG_USER: postgres
          PG_PASSWORD: postgres
          REDIS_HOST: redis
          REDIS_PORT: 6379
          DB_NAME: rate_limiter
